Add  License view logic

diff --git a/simple/funcs b/simple/funcs
--- a/simple/funcs
+++ b/simple/funcs
@@ -14,6 +14,38 @@ function echoBold () {
     echo -en  $'\e[1m'"${1}"$'\e[0m'
 }
 
+function display_msg(){
+    msg=$@
+    echoBold "${msg}"
+    exit 1
+}
+
+function viewLicenseText(){
+
+  echo "PLEASE READ THE BELOW \"WSO2 SOFTWARE LICENSE AGREEMENT\" CAREFULLY BEFORE COMPLETING THE INSTALLATION PROCESS AND USING THE SOFTWARE."
+
+  sleep 2s
+
+  less ${license_text}
+
+  while [[ -z ${isAgree} ]]
+  do
+  read -p "Do you accept license terms ? (Y|n): " isAgree
+      if [[ ${isAgree} == Y || ${isAgree} == y ]]; then
+          echo "Continuing with installation ..."
+      elif [[ ${isAgree} == N || ${isAgree} == n ]]; then
+          echo "Installation aborted since you didn't accept the license terms"
+          echo "Aborting Installation ..."
+          sleep 1s
+          exit 0
+      else
+          echo "Please enter Y or N to continue"
+          isAgree=""
+      fi
+  done
+
+}
+
 function st(){
   cycles=${1}
   i=0
@@ -223,6 +255,9 @@ function deploy(){
 
     #displaying wso2 product name
     product_name
+
+    #create and view EULA text
+    createLicenseText
 
     get_creds  # get wso2 subscription parameters
 
